logging:
  level:
    org:
      springframework:
        security: DEBUG
        
        
application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer 
    tokenExpirationDay: 14